- name: launch one nova instance
  connection: local
  hosts: local
  vars_files:
   - vars/metacloud_vars.yml

  tasks: 
 
  - name: Ensure New server is up. 
    nova_compute:
      state: present
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      name: demo-server
      image_id: "{{ coreos_image_id }}"
      key_name: "{{ keypair }}"
      #m1.small is 5
      #m1.medium is id 1
      flavor_id: 5 
      #auto_floating_ip: yes
      security_groups: "{{ security_group }}"
      floating_ip_pools:
      - "{{ floating_ip_pool }}"
      wait_for: 200
    register: instance
