- name: launch a nova instance
  connection: local
  hosts: local
  vars_files:
   - vars/metacloud_vars.yml

  tasks: 
  #- debug: msg="{{ lookup('env', 'OS_USERNAME') }}"
  #  register: os_username
  #- debug: msg="{{ lookup('env', 'OS_PASSWORD') }}"
  #- debug: msg="{{ lookup('env', 'OS_AUTH_URL') }}"
  #- debug: msg="{{ lookup('env', 'OS_TENANT_ID') }}"
  #- debug: msg="{{ lookup('env', 'OS_TENANT_NAME') }}"
 
  - name: Ensure Gitlab server is up
    nova_compute:
      state: present
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      name: docker-gitlab-jenkins
      image_id: "{{ coreos_image_id }}"
      key_name: "{{ keypair }}"
      #m1.small is 5
      #m1.medium is id 1
      flavor_id: 1 
      #auto_floating_ip: yes
      security_groups: "{{ security_group }}"
      floating_ip_pools:
      - "{{ floating_ip_pool }}"
      wait_for: 200
    register: instance
